---
- name: make base folder
  file:
    path: "{{youtranscript_site_root}}"
    state: directory
    owner: 'www-data'
    group: 'www-data'
- name: clone the repo
  register: youtranscript_clone
  become_user: 'www-data'
  git:
    repo: https://github.com/thavelick/youtranscript.git
    dest: "{{youtranscript_site_root}}/public_html"
    version: main
    single_branch: true
    depth: 1
    clone: true
    update: true
- name: configure service
  include_role: {name: service_standard}
  vars: {service_name: youtranscript}
- name: make the log folder
  become_user: 'www-data'
  file:
    path: "{{youtranscript_site_root}}/logs"
    state: directory
- name: copy nginx site config
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/{{youtranscript_domain}}
  register: youtranscript_nginx
- name: enable the nginx site config
  file:
    dest: /etc/nginx/sites-enabled/{{youtranscript_domain}}
    state: link
    src: /etc/nginx/sites-available/{{youtranscript_domain}}
- name: restart nginx
  when: youtranscript_nginx.changed
  service:
    name: nginx
    state: restarted
