- name: create the systemd service
  template:
    src: templates/{{service_name}}.service.j2
    dest: /etc/systemd/system/{{service_name}}.service
- name: start and enable the systemd service
  service:
    name: "{{service_name}}"
    enabled: true
    state: started
