---
- name: setup jellyfin
  include_role: {name: vharmers.jellyfin}
- name: configure nginx forward
  include_role: {name: nginx_forward}
  vars:
    domain: "{{jellyfin_domain}}"
    port: 8096
    nginx_conf_template: jellyfin_nginx.conf.j2
