---
- name: Setup Home Server
  hosts: all
  become: true
  vars:
    backup_staging_directory: /var/www/backup-staging
    home_assistant_domain: assistant.{{parent_domain}}
    home_assistant_site_root: /var/www/assistant.{{parent_domain}}
    jellyfin_domain: jellyfin.{{parent_domain}}
    jellyseerr_base_directory: /var/www/jellyseerr
    jellyseerr_domain: jellyseerr.{{parent_domain}}
    just_auth_site_root: /var/www/just_auth
    just_bangs_domain: bangs.{{parent_domain}}
    just_bangs_site_root: /var/www/bangs.{{parent_domain}}
    kiwix_domain: kiwix.{{parent_domain}}
    kiwix_site_root: /var/www/kiwix.{{parent_domain}}
    miniflux_domain: miniflux.{{parent_domain}}
    miniflux_site_root: /var/www/miniflux.{{parent_domain}}
    nextcloud_domain: nextcloud.{{parent_domain}}
    nextcloud_base_directory: /var/www/nextcloud
    nextcloud_data_directory: "{{nextcloud_base_directory}}/data"
    nextcloud_config_directory: "{{nextcloud_base_directory}}/config"
    onlyoffice_domain: onlyoffice.{{parent_domain}}
    prowlarr_base_directory: /var/www/prowlarr
    radarr_base_directory: /var/www/radarr
    radarr_data_directory: "{{transmission_base_directory}}/downloads"
    searxng_domain: searxng.{{parent_domain}}
    searxng_site_root: /var/www/searxng.{{parent_domain}}
    transmission_domain: transmission.{{parent_domain}}
    transmission_base_directory: /var/www/transmission
    tubesync_domain: tubesync.{{parent_domain}}
    tubesync_base_directory: /var/www/tubesync
    tubesync_config_directory: "{{tubesync_base_directory}}/config"
    wallabag_domain: articles.{{parent_domain}}
    wallabag_site_root: /var/www/articles.{{parent_domain}}
    wallabag_server_name: "Tristan's Wallabag"
    web_server_ip: "{{ansible_default_ipv4.address}}"
    youtranscript_domain: youtranscript.{{parent_domain}}
    youtranscript_site_root: /var/www/youtranscript.{{parent_domain}}
    miniflux_linux_user: miniflux
    miniflux_db_user_name: miniflux_db_user
    miniflux_db: miniflux_db
    miniflux_admin_name: admin
    miniflux_port: 8050
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
          - "home.{{parent_domain}}"
          - "{{home_assistant_domain}}"
          - "{{jellyfin_domain}}"
          - "{{jellyseerr_domain}}"
          - "{{just_bangs_domain}}"
          - "{{kiwix_domain}}"
          - "{{miniflux_domain}}"
          - "{{nextcloud_domain}}"
          - "{{onlyoffice_domain}}"
          - "{{searxng_domain}}"
          - "{{tubesync_domain}}"
          - "{{wallabag_domain}}"
          - "{{youtranscript_domain}}"
  roles:
    - {role: common, tags: common}
    - {role: geerlingguy.certbot, tags: certbot}
    - {role: geerlingguy.docker, tags: docker}
    - {role: home_assistant, tags: home_assistant}
    - {role: jellyfin, tags: jellyfin}
    - {role: jellyseerr, tags: jellyseerr}
    - {role: just_bangs, tags: just_bangs}
    - {role: kiwix, tags: kiwix}
    - {role: miniflux, tags: miniflux}
    - {role: nextcloud, tags: nextcloud}
    - {role: onlyoffice, tags: onlyoffice}
    - {role: prowlarr, tags: prowlarr}
    - {role: radarr, tags: radarr}
    - {role: readarr, tags: readarr}
    - {role: searxng, tags: searxng}
    - {role: tubesync, tags: tubesync}
    - {role: youtranscript, tags: youtranscript}
    - {role: transmission, tags: transmission}
    - {role: wallabag, tags: wallabag}
    - {role: dnsmasq, tags: dnsmasq}
    - {role: dynamicdns, tags: dynamicdns}
    - {role: backup, tags: backup}
