
- name: Setup Home Server
  hosts: all
  become: yes
  roles:
    - role: common
      tags: searxng
    - role: geerlingguy.certbot
    - role: chatpad
    - role: just_bangs
    - role: kiwix
    - role: miniflux
    - role: navidrome
    - role: searxng
      tags: searxng
    - role: youtranscript
    - role: wallabag
    - role: dynamicdns
  vars:
    chatpad_domain: chatpad.{{parent_domain}}
    chatpad_site_root: /var/www/chatpad.{{parent_domain}}
    just_bangs_domain: bangs.{{parent_domain}}
    just_bangs_site_root: /var/www/bangs.{{parent_domain}}
    kiwix_domain: kiwix.{{parent_domain}}
    kiwix_site_root: /var/www/kiwix.{{parent_domain}}
    miniflux_domain: miniflux.{{parent_domain}}
    miniflux_site_root: /var/www/miniflux.{{parent_domain}}
    navidrome_domain: navidrome.{{parent_domain}}
    navidrome_site_root: /var/www/navidrome.{{parent_domain}}
    searxng_domain: searxng.{{parent_domain}}
    searxng_site_root: /var/www/searxng.{{parent_domain}}
    wallabag_domain: articles.{{parent_domain}}
    wallabag_site_root: /var/www/articles.{{parent_domain}}
    wallabag_server_name: "Tristan's Wallabag"
    youtranscript_domain: youtranscript.{{parent_domain}}
    youtranscript_site_root: /var/www/youtranscript.{{parent_domain}}
    miniflux_linux_user: miniflux
    miniflux_db_user_name: miniflux_db_user
    miniflux_db: miniflux_db
    miniflux_admin_name: admin
    miniflux_port: 8050
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
        - "home.{{parent_domain}}"
        - "{{chatpad_domain}}"
        - "{{just_bangs_domain}}"
        - "{{kiwix_domain}}"
        - "{{miniflux_domain}}"
        - "{{navidrome_domain}}"
        - "{{searxng_domain}}"
        - "{{wallabag_domain}}"
        - "{{youtranscript_domain}}"