
- name: Setup Home Server
  hosts: all
  become: yes
  roles:
    - common
    - geerlingguy.certbot
    - just_bangs
    - wallabag
  vars:
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
        - "home.tristanhavelick.com"
        - "{{just_bangs_domain}}"
        - "{{wallabag_domain}}"
