---
- name: Setup Home Server
  hosts: all
  become: true
  vars:
    chatpad_domain: chatpad.{{parent_domain}}
    chatpad_site_root: /var/www/chatpad.{{parent_domain}}
    jellyfin_domain: jellyfin.{{parent_domain}}
    just_bangs_domain: bangs.{{parent_domain}}
    just_bangs_site_root: /var/www/bangs.{{parent_domain}}
    kiwix_domain: kiwix.{{parent_domain}}
    kiwix_site_root: /var/www/kiwix.{{parent_domain}}
    miniflux_domain: miniflux.{{parent_domain}}
    miniflux_site_root: /var/www/miniflux.{{parent_domain}}
    navidrome_domain: navidrome.{{parent_domain}}
    navidrome_site_root: /var/www/navidrome.{{parent_domain}}
    searxng_domain: searxng.{{parent_domain}}
    searxng_site_root: /var/www/searxng.{{parent_domain}}
    wallabag_domain: articles.{{parent_domain}}
    wallabag_site_root: /var/www/articles.{{parent_domain}}
    wallabag_server_name: "Tristan's Wallabag"
    youtranscript_domain: youtranscript.{{parent_domain}}
    youtranscript_site_root: /var/www/youtranscript.{{parent_domain}}
    ytdl_sub_user: jellyfin
    ytdl_sub_root: /var/www/ytdl_sub
    miniflux_linux_user: miniflux
    miniflux_db_user_name: miniflux_db_user
    miniflux_db: miniflux_db
    miniflux_admin_name: admin
    miniflux_port: 8050
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
          - "home.{{parent_domain}}"
          - "{{chatpad_domain}}"
          - "{{jellyfin_domain}}"
          - "{{just_bangs_domain}}"
          - "{{kiwix_domain}}"
          - "{{miniflux_domain}}"
          - "{{navidrome_domain}}"
          - "{{searxng_domain}}"
          - "{{wallabag_domain}}"
          - "{{youtranscript_domain}}"
  roles:
    - {role: common, tags: common}
    - {role: geerlingguy.certbot, tags: certbot}
    - {role: chatpad, tags: chatpad}
    - {role: jellyfin, tags: jellyfin}
    - {role: just_bangs, tags: just_bangs}
    - {role: kiwix, tags: kiwix}
    - {role: miniflux, tags: miniflux}
    - {role: navidrome, tags: navidrome}
    - {role: searxng, tags: searxng}
    - {role: youtranscript, tags: youtranscript}
    # - {role: ytdl_sub, tags: ytdl_sub}
    - {role: wallabag, tags: wallabag}
    - {role: dynamicdns, tags: dynamicdns}
