
- name: Setup Home Server
  hosts: all
  become: yes
  roles:
    - common
    - postgres
    - geerlingguy.certbot
    - just_bangs
    - kiwix
    - youtranscript
    - wallabag
  vars:
    just_bangs_domain: bangs.{{parent_domain}}
    just_bangs_site_root: /var/www/bangs.{{parent_domain}}
    kiwix_domain: kiwix.{{parent_domain}}
    kiwix_site_root: /var/www/kiwix.{{parent_domain}}
    wallabag_domain: articles.{{parent_domain}}
    wallabag_site_root: /var/www/articles.{{parent_domain}}
    wallabag_server_name: "Tristan's Wallabag"
    youtranscript_domain: youtranscript.{{parent_domain}}
    youtranscript_site_root: /var/www/youtranscript.{{parent_domain}}

    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
        - "home.{{parent_domain}}"
        - "{{just_bangs_domain}}"
        - "{{kiwix_domain}}"
        - "{{wallabag_domain}}"
        - "{{youtranscript_domain}}"
