---
- name: create directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{nextcloud_user}}"
    group: "{{nextcloud_user}}"
    mode: 0755
  loop:
    - "{{nextcloud_base_directory}}"
    - "{{nextcloud_data_directory}}"
    - "{{nextcloud_config_directory}}"
    - "{{nextcloud_base_directory}}/apps"
    - "{{nextcloud_base_directory}}/app-hooks"
    - "{{nextcloud_base_directory}}/app-hooks/post_installation"

# Although it looks like this should run automatically, it doesn't.
# after nextcloud is installed, you have to docker exec into the container
# and run this manually,
- name: copy the onlyoffice install script
  template:
    src: templates/onlyoffice.sh.j2
    dest: "{{nextcloud_base_directory}}/app-hooks/post_installation/onlyoffice.sh"
    mode: 0755
- name: run the nextcloud container
  docker_container:
    name: nextcloud
    image: nextcloud:31
    pull: true
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "9787:80"
    volumes:
      - "{{nextcloud_data_directory}}:/var/www/html/data:rw"
      - "{{nextcloud_config_directory}}:/var/www/html/config"
      - "{{nextcloud_base_directory}}/apps:/var/www/html/custom_apps"
      - "{{nextcloud_base_directory}}/app-hooks/post_installation:/docker-entrypoint-hooks.d/post-installation"
    env:
      SQLITE_DATABASE: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: "{{nextcloud_domain}}"
      NEXTCLOUD_ADMIN_USER: "{{nextcloud_admin_user}}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{nextcloud_admin_password}}"
      HTTP_X_FORWARDED_PROTO: https
      HTTP_X_FORWARDED_HOST: "{{nextcloud_domain}}"
      OVERWRITEHOST: "{{nextcloud_domain}}"
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: "172.16.0.0/12"
  register: nextcloud_container_result

# Wait for container to potentially initialize after start/restart, but only if it was changed
- name: pause for 2 minutes if container was updated
  pause:
    minutes: 2
  when: nextcloud_container_result.changed
# Run upgrade command - safe to run even if no upgrade needed
- name: run nextcloud upgrade command
  command: docker exec --user www-data nextcloud php occ upgrade
  register: occ_upgrade_result
  changed_when: "'Nextcloud is already latest version' not in occ_upgrade_result.stdout"
  failed_when: occ_upgrade_result.rc != 0 and 'Nextcloud is not installed' not in occ_upgrade_result.stderr
# Ensure maintenance mode is off - safe to run even if already off
- name: ensure maintenance mode is off
  command: docker exec --user www-data nextcloud php occ maintenance:mode --off
  changed_when: false # This command doesn't reliably indicate change
- name: configure nginx
  include_role: {name: nginx_standard}
  vars:
    domain: "{{nextcloud_domain}}"
    port: 9787
    nginx_conf_template: nextcloud_nginx.conf.j2
