// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var colyseus_server_RoomOf = require("colyseus").Room;
class GameRoom extends colyseus_server_RoomOf {
	constructor(presence) {
		super(presence);
	}
	onCreate(options) {
		this.maxClients = 6;
		this.setState(new GameState());
		console.log("hxsrc/GameRoom.hx:17:","start room: " + this.roomId + ":" + this.roomName);
		let _gthis = this;
		this.onMessage("move",function(client,data) {
			let player = _gthis.state.players.get(client.sessionId);
			if(player != null) {
				player.x = data.x;
				player.y = data.y;
				player.velocityX = data.velocityX;
				player.velocityY = data.velocityY;
			}
		});
		this.onMessage("player_name_changed",function(client,data) {
			let player = _gthis.state.players.get(client.sessionId);
			if(player != null) {
				player.name = data.name;
			}
		});
		this.onMessage("fish_spawn",function(client,data) {
			console.log("hxsrc/GameRoom.hx:46:","" + client.sessionId + ": sent \"fish_spawn\" message: " + JSON.stringify(data));
			_gthis.state.fish.set(data.id,new FishState(data.x,data.y));
		});
		this.onMessage("throw_rock",function(client,data) {
			console.log("hxsrc/GameRoom.hx:52:","" + client.sessionId + ": sent \"throw_rock\": targetX=" + Std.string(data.targetX) + " targetY=" + Std.string(data.targetY) + " big=" + Std.string(data.big) + " dir=" + Std.string(data.dir));
			_gthis.broadcast("throw_rock",{ sessionId : client.sessionId, targetX : data.targetX, targetY : data.targetY, big : data.big, dir : data.dir},{ except : client});
		});
		this.onMessage("rock_splash",function(client,data) {
			console.log("hxsrc/GameRoom.hx:64:","" + client.sessionId + ": sent \"rock_splash\": x=" + Std.string(data.x) + " y=" + Std.string(data.y) + " big=" + Std.string(data.big));
			_gthis.broadcast("rock_splash",{ x : data.x, y : data.y, big : data.big},{ except : client});
		});
		this.onMessage("fish_move",function(client,data) {
			let fish = _gthis.state.fish.get(data.id);
			if(fish != null) {
				fish.x = data.x;
				fish.y = data.y;
			}
		});
		this.onMessage("fish_despawn",function(client,data) {
			console.log("hxsrc/GameRoom.hx:79:","" + client.sessionId + ": sent \"fish_despawn\": id=" + Std.string(data.id) + " respawnTime=" + Std.string(data.respawnTime));
			_gthis.broadcast("fish_despawn",{ id : data.id, respawnTime : data.respawnTime},{ except : client});
		});
		this.onMessage("skin_changed",function(client,data) {
			console.log("hxsrc/GameRoom.hx:85:","" + client.sessionId + ": sent \"skin_changed\" message: skinIndex=" + Std.string(data.skinIndex));
			let player = _gthis.state.players.get(client.sessionId);
			if(player != null) {
				player.skinIndex = data.skinIndex;
			}
		});
		this.onMessage("score_update",function(client,data) {
			console.log("hxsrc/GameRoom.hx:94:","" + client.sessionId + ": sent \"score_update\" message: score=" + Std.string(data.score));
			let player = _gthis.state.players.get(client.sessionId);
			if(player != null) {
				player.score = data.score;
			}
		});
		this.onMessage("world_items",function(client,data) {
			if(client.sessionId != _gthis.state.hostSessionId) {
				return;
			}
			console.log("hxsrc/GameRoom.hx:106:","" + client.sessionId + ": sent \"world_items\"");
			_gthis.broadcast("world_items",data,{ except : client});
		});
		this.onMessage("item_pickup",function(client,data) {
			console.log("hxsrc/GameRoom.hx:112:","" + client.sessionId + ": sent \"item_pickup\": itemType=" + Std.string(data.itemType) + " index=" + Std.string(data.index));
			_gthis.broadcast("item_pickup",{ sessionId : client.sessionId, itemType : data.itemType, index : data.index},{ except : client});
		});
		this.onMessage("weed_burst",function(client,data) {
			console.log("hxsrc/GameRoom.hx:118:","" + client.sessionId + ": sent \"weed_burst\": index=" + Std.string(data.index));
			_gthis.broadcast("weed_burst",{ sessionId : client.sessionId, index : data.index},{ except : client});
		});
		this.onMessage("bush_rustle",function(client,data) {
			console.log("hxsrc/GameRoom.hx:124:","" + client.sessionId + ": sent \"bush_rustle\": index=" + Std.string(data.index));
			_gthis.broadcast("bush_rustle",{ index : data.index, dirX : data.dirX, dirY : data.dirY},{ except : client});
		});
		this.onMessage("worm_killed",function(client,data) {
			console.log("hxsrc/GameRoom.hx:130:","" + client.sessionId + ": sent \"worm_killed\"");
			_gthis.broadcast("worm_killed",{ sessionId : client.sessionId},{ except : client});
		});
		this.onMessage("fish_sold",function(client,data) {
			console.log("hxsrc/GameRoom.hx:136:","" + client.sessionId + ": sent \"fish_sold\" message: fishType=" + Std.string(data.fishType) + " lengthCm=" + Std.string(data.lengthCm) + " value=" + Std.string(data.value));
			_gthis.broadcast("fish_sold",{ sessionId : client.sessionId, fishType : data.fishType, lengthCm : data.lengthCm, value : data.value},{ except : client});
		});
		this.onMessage("cast_line",function(client,data) {
			console.log("hxsrc/GameRoom.hx:147:","" + client.sessionId + ": sent \"cast_line\" message: " + JSON.stringify(data));
			_gthis.broadcast("cast_line",{ sessionId : client.sessionId, x : data.x, y : data.y, dir : data.dir},{ except : client});
		});
		this.onMessage("fish_caught",function(client,data) {
			console.log("hxsrc/GameRoom.hx:159:","" + client.sessionId + ": sent \"fish_caught\": fishId=" + Std.string(data.fishId) + " catcher=" + Std.string(data.catcherSessionId));
			_gthis.broadcast("fish_caught",{ sessionId : data.catcherSessionId, fishId : data.fishId});
		});
		this.onMessage("line_pulled",function(client,data) {
			console.log("hxsrc/GameRoom.hx:165:","" + client.sessionId + ": sent \"line_pulled\" message");
			_gthis.broadcast("line_pulled",{ sessionId : client.sessionId});
		});
		this.onMessage("spawn_locations",function(client,data) {
			if(client.sessionId != _gthis.state.hostSessionId) {
				return;
			}
			console.log("hxsrc/GameRoom.hx:174:","" + client.sessionId + ": sent \"spawn_locations\"");
			_gthis.broadcast("spawn_locations",data,{ except : client});
		});
		this.onMessage("world_setup",function(client,data) {
			if(client.sessionId != _gthis.state.hostSessionId) {
				return;
			}
			let bushArray = data.bushes;
			let _g_current = 0;
			let _g_array = bushArray;
			while(_g_current < _g_array.length) {
				let _g_value = _g_array[_g_current];
				let _g_key = _g_current++;
				let i = _g_key;
				let bush = _g_value;
				_gthis.state.bushes.set(i == null ? "null" : "" + i,new BushState(bush.x,bush.y));
			}
			_gthis.state.shopX = data.shopX;
			_gthis.state.shopY = data.shopY;
			_gthis.state.shopReady = true;
		});
		this.onMessage("round_update",function(client,data) {
			console.log("hxsrc/GameRoom.hx:193:","" + client.sessionId + ": sent \"round_update\" message: " + JSON.stringify(data));
			if(data != null) {
				let newData = new RoundState();
				newData.status = _gthis.state.round.status;
				newData.currentRound = _gthis.state.round.currentRound;
				newData.totalRounds = _gthis.state.round.totalRounds;
				if(data.status != null) {
					console.log("hxsrc/GameRoom.hx:201:","update round status: " + _gthis.state.round.status + " -> " + Std.string(data.status));
					newData.status = data.status;
					let jsIterator = _gthis.state.players.entries();
					let _g_jsIterator = jsIterator;
					let _g_lastStep = jsIterator.next();
					while(!_g_lastStep.done) {
						let v = _g_lastStep.value;
						_g_lastStep = _g_jsIterator.next();
						let _g = v;
						let sId = _g[0];
						let pp = _g[1];
						pp.ready = false;
					}
				}
				if(data.currentRound != null) {
					newData.currentRound = data.currentRound;
				}
				if(data.totalRounds != null) {
					newData.totalRounds = data.totalRounds;
				}
				_gthis.state.round = newData;
			}
		});
		this.onMessage("player_ready",function(client,_) {
			if(_gthis.state.round.status != RoundState.STATUS_LOBBY && _gthis.state.round.status != RoundState.STATUS_PRE_ROUND && _gthis.state.round.status != RoundState.STATUS_POST_ROUND) {
				return;
			}
			let player = _gthis.state.players.get(client.sessionId);
			if(player != null) {
				player.ready = true;
			}
			let ready = true;
			let jsIterator = _gthis.state.players.entries();
			let _g_jsIterator = jsIterator;
			let _g_lastStep = jsIterator.next();
			while(!_g_lastStep.done) {
				let v = _g_lastStep.value;
				_g_lastStep = _g_jsIterator.next();
				let _g = v;
				let sId = _g[0];
				let pp = _g[1];
				if(!pp.ready) {
					ready = false;
					break;
				}
			}
			if(ready) {
				_gthis.broadcast("players_ready",true);
				let jsIterator = _gthis.state.players.entries();
				let _g_jsIterator = jsIterator;
				let _g_lastStep = jsIterator.next();
				while(!_g_lastStep.done) {
					let v = _g_lastStep.value;
					_g_lastStep = _g_jsIterator.next();
					let _g = v;
					let sId = _g[0];
					let pp = _g[1];
					pp.ready = false;
				}
				if(_gthis.state.round.status == RoundState.STATUS_LOBBY) {
					_gthis.lock();
				}
			}
		});
	}
	onJoin(client,options) {
		console.log("hxsrc/GameRoom.hx:252:","player joined: " + client.sessionId);
		this.state.players.set(client.sessionId,new PlayerState());
		if(this.state.hostSessionId == null || this.state.hostSessionId == "") {
			this.state.hostSessionId = client.sessionId;
			console.log("hxsrc/GameRoom.hx:258:","host set " + client.sessionId);
		}
		return null;
	}
	onLeave(client,code) {
		console.log("hxsrc/GameRoom.hx:265:","player left: " + client.sessionId);
		console.log("hxsrc/GameRoom.hx:266:","successful clear: " + Std.string(this.state.players.delete(client.sessionId)));
		if(client.sessionId == this.state.hostSessionId) {
			if(this.state.players.size <= 0) {
				this.state.hostSessionId = null;
			} else {
				let sIds = [];
				let jsIterator = this.state.players.entries();
				let _g_jsIterator = jsIterator;
				let _g_lastStep = jsIterator.next();
				while(!_g_lastStep.done) {
					let v = _g_lastStep.value;
					_g_lastStep = _g_jsIterator.next();
					let _g = v;
					let sId = _g[0];
					let _ = _g[1];
					sIds.push(sId);
				}
				let sIdx = Std.random(this.state.players.size);
				this.state.hostSessionId = sIds[sIdx];
			}
			console.log("hxsrc/GameRoom.hx:281:","host changed " + client.sessionId + " -> " + this.state.hostSessionId);
			if(this.state.hostSessionId == null) {
				console.log("hxsrc/GameRoom.hx:284:","disconnect room: " + this.roomId + ":" + this.roomName);
				this.disconnect();
			}
		}
		return null;
	}
}
GameRoom.__name__ = true;
var colyseus_server_schema_Schema = require("@colyseus/schema").Schema;
var colyseus_server_schema_ExternDecorator = require("@colyseus/schema");
class BushState extends colyseus_server_schema_Schema {
	constructor(x,y) {
		super();
		this.x = x;
		this.y = y;
	}
}
BushState.__name__ = true;
class PlayerState extends colyseus_server_schema_Schema {
	constructor() {
		super();
		this.x = 0;
		this.y = 0;
		this.velocityX = 0;
		this.velocityY = 0;
		this.ready = false;
		this.name = "";
		this.skinIndex = -1;
		this.score = 0;
	}
}
PlayerState.__name__ = true;
class FishState extends colyseus_server_schema_Schema {
	constructor(x,y) {
		super();
		this.x = x;
		this.y = y;
	}
}
FishState.__name__ = true;
class RoundState extends colyseus_server_schema_Schema {
	constructor() {
		super();
		this.status = RoundState.STATUS_LOBBY;
		this.currentRound = 0;
		this.totalRounds = 0;
	}
}
RoundState.__name__ = true;
class GameState extends colyseus_server_schema_Schema {
	constructor() {
		super();
		this.players = new colyseus_server_schema_MapSchema();
		this.fish = new colyseus_server_schema_MapSchema();
		this.round = new RoundState();
		this.bushes = new colyseus_server_schema_MapSchema();
		this.shopX = 0;
		this.shopY = 0;
		this.shopReady = false;
	}
}
GameState.__name__ = true;
class Main {
	static main() {
		let port = 2567;
		let gameServer = new colyseus_server_Server({ });
		gameServer.define("game_room",GameRoom);
		gameServer.listen(port,"0.0.0.0").then(function(_) {
			console.log("hxsrc/Main.hx:9:","Listening on ws://localhost:" + port);
		});
	}
}
Main.__name__ = true;
Math.__name__ = true;
class Std {
	static string(s) {
		return js_Boot.__string_rec(s,"");
	}
	static random(x) {
		if(x <= 0) {
			return 0;
		} else {
			return Math.floor(Math.random() * x);
		}
	}
}
Std.__name__ = true;
var colyseus_server_Server = require("colyseus").Server;
var colyseus_server_schema_MapSchema = require("@colyseus/schema").MapSchema;
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
haxe_iterators_ArrayIterator.__name__ = true;
class js_Boot {
	static __string_rec(o,s) {
		if(o == null) {
			return "null";
		}
		if(s.length >= 5) {
			return "<...>";
		}
		let t = typeof(o);
		if(t == "function" && (o.__name__ || o.__ename__)) {
			t = "object";
		}
		switch(t) {
		case "function":
			return "<function>";
		case "object":
			if(((o) instanceof Array)) {
				let str = "[";
				s += "\t";
				let _g = 0;
				let _g1 = o.length;
				while(_g < _g1) {
					let i = _g++;
					str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
				}
				str += "]";
				return str;
			}
			let tostr;
			try {
				tostr = o.toString;
			} catch( _g ) {
				return "???";
			}
			if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
				let s2 = o.toString();
				if(s2 != "[object Object]") {
					return s2;
				}
			}
			let str = "{\n";
			s += "\t";
			let hasp = o.hasOwnProperty != null;
			let k = null;
			for( k in o ) {
			if(hasp && !o.hasOwnProperty(k)) {
				continue;
			}
			if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
				continue;
			}
			if(str.length != 2) {
				str += ", \n";
			}
			str += s + k + " : " + js_Boot.__string_rec(o[k],s);
			}
			s = s.substring(1);
			str += "\n" + s + "}";
			return str;
		case "string":
			return o;
		default:
			return String(o);
		}
	}
}
js_Boot.__name__ = true;
class js_node_KeyValue {
	static get_key(this1) {
		return this1[0];
	}
	static get_value(this1) {
		return this1[1];
	}
}
{
	(colyseus_server_schema_ExternDecorator.type("float32"))(BushState.prototype,"x");
	(colyseus_server_schema_ExternDecorator.type("float32"))(BushState.prototype,"y");
}
{
	(colyseus_server_schema_ExternDecorator.type("float32"))(PlayerState.prototype,"x");
	(colyseus_server_schema_ExternDecorator.type("float32"))(PlayerState.prototype,"y");
	(colyseus_server_schema_ExternDecorator.type("float32"))(PlayerState.prototype,"velocityX");
	(colyseus_server_schema_ExternDecorator.type("float32"))(PlayerState.prototype,"velocityY");
	(colyseus_server_schema_ExternDecorator.type("boolean"))(PlayerState.prototype,"ready");
	(colyseus_server_schema_ExternDecorator.type("string"))(PlayerState.prototype,"name");
	(colyseus_server_schema_ExternDecorator.type("int8"))(PlayerState.prototype,"skinIndex");
	(colyseus_server_schema_ExternDecorator.type("int32"))(PlayerState.prototype,"score");
}
{
	(colyseus_server_schema_ExternDecorator.type("float32"))(FishState.prototype,"x");
	(colyseus_server_schema_ExternDecorator.type("float32"))(FishState.prototype,"y");
}
{
	(colyseus_server_schema_ExternDecorator.type("string"))(RoundState.prototype,"status");
	(colyseus_server_schema_ExternDecorator.type("uint8"))(RoundState.prototype,"currentRound");
	(colyseus_server_schema_ExternDecorator.type("uint8"))(RoundState.prototype,"totalRounds");
}
{
	(colyseus_server_schema_ExternDecorator.type("string"))(GameState.prototype,"hostSessionId");
	(colyseus_server_schema_ExternDecorator.type({ map : PlayerState}))(GameState.prototype,"players");
	(colyseus_server_schema_ExternDecorator.type({ map : FishState}))(GameState.prototype,"fish");
	(colyseus_server_schema_ExternDecorator.type(RoundState))(GameState.prototype,"round");
	(colyseus_server_schema_ExternDecorator.type({ map : BushState}))(GameState.prototype,"bushes");
	(colyseus_server_schema_ExternDecorator.type("float32"))(GameState.prototype,"shopX");
	(colyseus_server_schema_ExternDecorator.type("float32"))(GameState.prototype,"shopY");
	(colyseus_server_schema_ExternDecorator.type("boolean"))(GameState.prototype,"shopReady");
}
{
	String.__name__ = true;
	Array.__name__ = true;
}
js_Boot.__toStr = ({ }).toString;
RoundState.STATUS_INACTIVE = "inactive";
RoundState.STATUS_LOBBY = "lobby";
RoundState.STATUS_PRE_ROUND = "pre_round";
RoundState.STATUS_ACTIVE = "active";
RoundState.STATUS_POST_ROUND = "post_round";
RoundState.STATUS_END_GAME = "end_game";
Main.main();
})({});
