---
- name: install kiwix tools (includes kiwix-server)
  apt:
    name:
      - kiwix-tools
- name: make all the folders
  file:
    path: "{{item}}"
    state: directory
    owner: 'www-data'
    group: 'www-data'
  with_items:
    - "{{kiwix_site_root}}"
    - "{{kiwix_site_root}}/data"
    - "{{kiwix_site_root}}/scripts"
- name: copy the start script (with exec permissions)
  copy:
    src: files/start.sh
    dest: "{{kiwix_site_root}}/scripts/start.sh"
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'
- name: create the systemd service
  template:
    src: templates/kiwix.service.j2
    dest: /etc/systemd/system/kiwix.service
- name: start and enable the systemd service
  service:
    name: kiwix
    enabled: true
    state: started
- name: configure nginx forward
  include_role: {name: nginx_forward}
  vars: {domain: "{{kiwix_domain}}", port: 8181}
