---
- name: install kiwix tools (includes kiwix-server)
  apt:
    name:
      - kiwix-tools
- name: make all the folders
  file:
    path: "{{item}}"
    state: directory
    owner: 'www-data'
    group: 'www-data'
  with_items:
    - "{{kiwix_site_root}}"
    - "{{kiwix_site_root}}/data"
    - "{{kiwix_site_root}}/scripts"
- name: copy the start script (with exec permissions)
  copy:
    src: files/start.sh
    dest: "{{kiwix_site_root}}/scripts/start.sh"
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'
- name: configure service
  include_role: {name: service_standard}
  vars: {service_name: kiwix}
- name: configure nginx
  include_role: {name: nginx_standard}
  vars: {domain: "{{kiwix_domain}}", service_port: 8181}
