---
- name: create directories
  file:
    path: "{{item}}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0755
  loop:
    - "{{firefly_site_root}}"
    - "{{firefly_site_root}}/database"
    - "{{firefly_site_root}}/upload"
- name: get the current timezone
  command: cat /etc/timezone
  register: current_timezone
  changed_when: false
- name: run the firefly container
  docker_container:
    name: firefly
    image: fireflyiii/core:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "4849:8080"
    volumes:
      - "{{firefly_site_root}}/upload:/var/www/html/storage/upload"
      - "{{firefly_site_root}}/database:/var/www/html/storage/database"
    env:
      APP_ENV: local
      APP_DEBUG: "false"
      SITE_OWNER: "{{admin_email}}"
      APP_KEY: "{{firefly_app_key}}"
      DEFAULT_LANGUAGE: en_US
      DEFAULT_LOCALE: equal
      TZ: "{{current_timezone.stdout}}"
      TRUSTED_PROXIES: "**"
      LOG_CHANNEL: stack
      APP_LOG_LEVEL: notice
      AUDIT_LOG_LEVEL: emergency
      DB_CONNECTION: sqlite
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      COOKIE_PATH: "/"
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: lax
      MAIL_MAILER: log
      MAIL_HOST: "null"
      MAIL_PORT: "2525"
      MAIL_FROM: changeme@example.com
      MAIL_USERNAME: "null"
      MAIL_PASSWORD: "null"
      MAIL_ENCRYPTION: "null"
      SEND_ERROR_MESSAGE: "true"
      SEND_REPORT_JOURNALS: "true"
      ENABLE_EXTERNAL_MAP: "false"
      ENABLE_EXTERNAL_RATES: "false"
      MAP_DEFAULT_LAT: "39.802016"
      MAP_DEFAULT_LONG: "-105.087233"
      MAP_DEFAULT_ZOOM: "6"
      AUTHENTICATION_GUARD: web
      AUTHENTICATION_GUARD_HEADER: REMOTE_USER
      DISABLE_FRAME_HEADER: "false"
      DISABLE_CSP_HEADER: "false"
      ALLOW_WEBHOOKS: "false"
      DKR_BUILD_LOCALE: "false"
      DKR_CHECK_SQLITE: "true"
      DKR_RUN_MIGRATION: "true"
      DKR_RUN_UPGRADE: "true"
      DKR_RUN_VERIFY: "true"
      DKR_RUN_REPORT: "true"
      DKR_RUN_PASSPORT_INSTALL: "true"
      APP_NAME: FireflyIII
      BROADCAST_DRIVER: log
      QUEUE_DRIVER: sync
      CACHE_PREFIX: firefly
      FIREFLY_III_LAYOUT: v1
      APP_URL: http://localhost
- name: set up the data importer
  docker_container:
    name: firefly-importer
    image: fireflyiii/data-importer:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "4850:8080"
    env:
      FIREFLY_III_URL: "https://{{firefly_domain}}"
      USE_CACHE: "false"
      IGNORE_DUPLICATE_ERRORS: "false"
      CAN_POST_AUTOIMPORT: "false"
      CAN_POST_FILES: "false"
      VERIFY_TLS_SECURITY: "true"
      CONNECTION_TIMEOUT: "31.41"
      APP_ENV: local
      APP_DEBUG: "false"
      LOG_CHANNEL: stack
      LOG_RETURN_JSON: "false"
      LOG_LEVEL: debug
      TRUSTED_PROXIES: "**"
      TZ: "{{current_timezone.stdout}}"
      ENABLE_MAIL_REPORT: "false"
      EXPECT_SECURE_URL: "false"
      MAIL_DESTINATION: "noreply@example.com"
      MAIL_FROM_ADDRESS: noreply@example.com
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: "2525"
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: "null"
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: "120"
      IS_EXTERNAL: "false"
      REDIS_HOST: "127.0.0.1"
      REDIS_PASSWORD: "null"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      REDIS_CACHE_DB: "1"
      APP_NAME: DataImporter
      APP_URL: "http://localhost"
- name: configure nginx for firefly
  include_role: {name: nginx_standard}
  vars: {domain: "{{firefly_domain}}", port: 4849}
- name: configure nginx for firefly importer
  include_role: {name: nginx_standard}
  vars: {domain: "{{firefly_importer_domain}}", port: 4850}
