---
- name: run the chatpad container
  docker_container:
    name: chatpad
    image: ghcr.io/deiucanta/chatpad:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - 8012:80
- name: configure nginx for chatpad
  include_role: {name: nginx_standard}
  vars: {domain: "{{ chatpad_domain }}", port: 8012}
