---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day
- name: install common packages
  apt:
    name:
      - acl
      - curl
      - nginx
      - python3
      - sqlite3
      - vim
- name: copy nginx sever config
  register: nginx_config
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
- name: restart nginx
  when: nginx_config.changed
  service:
    name: nginx
    state: restarted
- name: set the timezone to mountain time
  timezone:
    name: America/Denver