---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400  # One day
- name: install common packages
  apt:
    name:
      - acl
      - curl
      - git
      - nginx
      - python3
      - python3-pip
      - python3-passlib
      - sqlite3
      - vim
- name: make the htpasswd file
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ nginx_username }}"
    password: "{{ nginx_password }}"
    owner: www-data
    group: www-data
    mode: 0640
- name: copy nginx sever config
  register: nginx_config
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
- name: restart nginx
  when: nginx_config.changed
  service:
    name: nginx
    state: restarted
- name: set the timezone to mountain time
  timezone:
    name: America/Denver
