---
- name: install searxng prerequisites
  apt:
    name:
      - python3-dev
      - python3-babel
      - python3-venv
      - uwsgi
      - uwsgi-plugin-python3
      - git
      - build-essential
      - libxslt-dev
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
- name: make all the folders
  file:
    path: "{{item}}"
    state: directory
    owner: 'www-data'
    group: 'www-data'
  with_items:
    - "{{searxng_site_root}}"
    - "{{searxng_site_root}}/src"
    - "{{searxng_site_root}}/conf"
- name: clone the repo
  register: searxng_clone
  become_user: 'www-data'
  git:
    repo: https://github.com/searxng/searxng
    dest: "{{searxng_site_root}}/src"
    single_branch: true
    depth: 1
    clone: true
    update: true
- name: create the virtualenv
  become_user: 'www-data'
  command: python3 -m venv "{{searxng_site_root}}/venv"
  when: searxng_clone.changed
- name: install searxng requirements
  become_user: 'www-data'
  pip:
    requirements: "{{searxng_site_root}}/src/requirements.txt"
    virtualenv: "{{searxng_site_root}}/venv"
  when: searxng_clone.changed
- name: copy the searxng config file
  become_user: 'www-data'
  register: searxng_config
  template:
    src: templates/searxng.yml.j2
    dest: "{{searxng_site_root}}/conf/searxng.yml"
- name: configure service
  include_role: {name: service_standard}
  vars: {service_name: searxng}
- name: restart the systemd service
  when: searxng_config.changed
  service:
    name: searxng
    state: restarted
- name: configure just auth
  include_role:
    name: just_auth
  vars:
    proxy_to_service_name: searxng
    password: "{{searxng_just_auth_password}}"
    salt: "{{searxng_just_auth_salt}}"
    auth_port: 8788
    app_port: 8888
- name: configure nginx
  include_role: {name: nginx_standard}
  vars: {domain: "{{searxng_domain}}", port: 8788}
