---
- name: Install dnsmasq
  apt:
    name:
      - dnsmasq
    state: present
    update_cache: true

- name: Configure dnsmasq
  template:
    src: templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart dnsmasq service
  service:
    name: dnsmasq
    state: restarted
