---
- name: create directories
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  loop:
    - "{{home_assistant_site_root}}"
    - "{{home_assistant_site_root}}/config"
    - "{{home_assistant_matter_data_directory}}"
- name: deploy home assistant configuration files
  copy:
    src: "{{item}}"
    dest: "{{home_assistant_site_root}}/config/{{item}}"
    mode: 0644
  loop:
    - configuration.yaml
    - automations.yaml
    - scripts.yaml
    - scenes.yaml
- name: deploy google service account
  template:
    src: SERVICE_ACCOUNT.json.j2
    dest: "{{home_assistant_site_root}}/config/SERVICE_ACCOUNT.json"
    mode: 0644
- name: get the current timezone
  command: cat /etc/timezone
  register: current_timezone
  changed_when: false
- name: Run home assistant container
  docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    pull: true
    state: started
    restart_policy: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - "{{home_assistant_site_root}}/config:/config"
      - /dev/snd:/dev/snd
      - /sys/class/thermal:/sys/class/thermal:ro
    env:
      TZ: "{{current_timezone.stdout}}"
- name: run matter server container
  docker_container:
    name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    pull: true
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{home_assistant_matter_data_directory}}:/data"
    env:
      TZ: "{{current_timezone.stdout}}"
- name: configure nginx
  include_role: {name: nginx_standard}
  vars: {domain: "{{home_assistant_domain}}", service_port: 8123}
