---
- name: create the miniflux database
  become_user: postgres
  postgresql_db:
    name: "{{miniflux_db}}"
- name: create a miniflux db user
  become_user: postgres
  postgresql_user:
    name: "{{miniflux_db_user_name}}"
    login_db: "{{miniflux_db}}"
    password: "{{miniflux_db_user_password}}"
    state: present
- name: give the miniflux db user privileges
  become_user: postgres
  postgresql_privs:
    login_db: postgres
    privs: ALL
    type: database
    obj: "{{miniflux_db}}"
    role: "{{miniflux_db_user_name}}"
- name: add miniflux repo
  become: true
  apt_repository:
    repo: "deb [trusted=yes] https://repo.miniflux.app/apt/ /"
    state: present
    filename: miniflux
    update_cache: true
- name: install miniflux
  become: true
  apt:
    name: miniflux
    state: present
- name: add miniflux linux user
  become: true
  user:
    name: "{{ miniflux_linux_user }}"
    home: "/var/empty"
    create_home: "no"
    system: "yes"
    shell: "/bin/false"
- name: create directory "/etc/miniflux.d"
  become: true
  file:
    path: /etc/miniflux.d
    state: directory
- name: copy miniflux.conf
  become: true
  register: miniflux_conf
  template:
    src: "miniflux.conf"
    dest: "/etc/miniflux.conf"
- name: start miniflux.service
  become: true
  systemd:
    name: miniflux
    state: restarted
    enabled: true
  when: miniflux_conf.changed
- name: configure nginx forward
  include_role: {name: nginx_standard}
  vars: {domain: "{{miniflux_domain}}", service_port: "{{miniflux_port}}"}
