---
- name: make base folder
  file:
    path: "{{just_bangs_site_root}}"
    state: directory
    owner: 'www-data'
    group: 'www-data'
- name: clone the repo
  register: just_bangs_clone
  become_user: 'www-data'
  git:
    repo: https://github.com/thavelick/just-bangs.git
    dest: "{{just_bangs_site_root}}/public_html"
    version: main
    single_branch: true
    depth: 1
    clone: true
    update: true
- name: check if the duckduckgo bangs file already exists
  register: bangs_file
  stat:
    path: "{{just_bangs_site_root}}/public_html/bang.js"
- name: pull down the duckduckgo bangs file (if it doesn't exist)
  become_user: 'www-data'
  when: not bangs_file.stat.exists
  get_url:
    url: https://duckduckgo.com/bang.js
    dest: "{{just_bangs_site_root}}/public_html/bang.js"
- name: copy the custom bangs file
  become_user: 'www-data'
  register: custom_bangs_file
  copy:
    src: files/custom-bang.js
    dest: "{{just_bangs_site_root}}/public_html/custom-bang.js"
- name: create the systemd service
  template:
    src: templates/just-bangs.service.j2
    dest: /etc/systemd/system/just-bangs.service
- name: start and enable the systemd service
  service:
    name: just-bangs
    enabled: true
    state: started
- name: restart the just bangs service
  when: custom_bangs_file.changed
  service:
    name: just-bangs
    state: restarted
- name: configure nginx forward
  include_role: {name: nginx_forward}
  vars: {domain: "{{just_bangs_domain}}", port: 8484}
