---
borg_backup_directory: /media/disk2/backup/home-server
ffmpegfs_source_directory: /media/disk2/podcasts
ffmpegfs_mount_directory: /media/podcasts_mp4
radarr_movies_directory: /media/disk2/movies
openvpn_provider: PIA
openvpn_config: ca_toronto
