---
- name: install wallabag dependencies
  apt:
    name:
      - build-essential
      - composer
      - gettext
      - git
      - php-bcmath
      - php-curl
      - php-fpm
      - php-gd
      - php-intl
      - php-sqlite3
      - php-tidy
      - php-xml
- name: make base folder
  file:
    path: "{{wallabag_site_root}}"
    owner: 'www-data'
    group: 'www-data'
    state: directory
- name: clone the repo
  register: wallabag_clone
  become_user: www-data
  git:
    repo: https://github.com/wallabag/wallabag.git
    dest: "{{wallabag_site_root}}/public_html"
    version: '2.6.7'
    single_branch: true
    depth: 1
    clone: true
    update: true
- name: copy parameters.yml
  register: wallabag_parameters
  template:
    src: templates/parameters.yml.j2
    dest: "{{wallabag_site_root}}/public_html/app/config/parameters.yml"
- name: fix permissions on the repo
  when: wallabag_clone.changed or wallabag_parameters.changed
  file:
    group: 'www-data'
    owner: 'www-data'
    path: "{{wallabag_site_root}}/public_html"
    state: directory
    recurse: true
- name: install php dependencies
  become_user: www-data
  composer:
    prefer_source: true
    no_dev: true
    no_scripts: true
    no_plugins: true
    working_dir: "{{wallabag_site_root}}/public_html"
- name: run the wallabag installer
  become_user: www-data
  when: wallabag_clone.changed
  shell: >
    /usr/bin/php {{wallabag_site_root}}/public_html/bin/console
    wallabag:install
    --env=prod
    --no-interaction
- name: set the wallabag admin password
  when: wallabag_clone.changed
  become_user: www-data
  shell: >
    /usr/bin/php {{wallabag_site_root}}/public_html/bin/console
    fos:user:change-password
    --env=prod
    {{wallabag_admin_user}}
    {{wallabag_admin_password}}
- name: make the log folder
  file:
    group: 'www-data'
    owner: 'www-data'
    path: "{{wallabag_site_root}}/logs"
    state: directory
- name: copy nginx site config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/{{wallabag_domain}}
  register: wallabag_nginx
- name: enable the nginx site config
  file:
    dest: /etc/nginx/sites-enabled/{{wallabag_domain}}
    state: link
    src: /etc/nginx/sites-available/{{wallabag_domain}}
- name: restart nginx
  when: wallabag_nginx.changed
  service:
    name: nginx
    state: restarted
